apiVersion: v1
kind: Service
metadata:
  name: app-one-service
spec:
  selector:
    app: app-one
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: app-two-service
spec:
  selector:
    app: app-two
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: app-three-service
spec:
  selector:
    app: app-three
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
