Vagrant.configure("2") do |config|
	config.vm.box = "debian/bookworm64"
	config.vm.box_version = "12.20250126.1"
	config.vm.provider "libvirt" do |libvirt|
		libvirt.cpus = 2
		libvirt.memory = 2048
	end
	config.vm.provision "shell", path: "scripts/install-dependencies.sh"

	config.vm.define "dhubleur" do |vm_config|
		vm_config.vm.hostname = "dhubleurS"
		vm_config.vm.network "private_network", ip: "192.168.56.110"
    vm_config.provision "file", source: "configurations", destination: "/configurations"
		vm_config.vm.provision "shell", path: "scripts/k3s-server.sh", args: ["192.168.56.110"]
	end
end
