Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.box_version = "12.20250126.1"
  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.define "shocquenS" do |control|
			control.vm.hostname = "shocquenS"
			control.vm.network "private_network", ip: "192.168.56.110"
		  control.vm.synced_folder "./confs", "/vagrant/confs", type: "virtualbox"
			control.vm.provider "virtualbox" do |v|
				v.name = "shocquenS"
				v.memory = 2048
				v.cpus = 2
			end
			control.vm.provision "shell", path: "./scripts/server.sh"
  end
end
