Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.box_version = "12.20250126.1"

  config.vm.define "shocquenS" do |control|
			control.vm.hostname = "shocquenS"
			control.vm.network "public_network", bridge: "eno1", ip: "192.168.56.110"
			control.vm.provider :libvirt do |v|
				v.name = "shocquenS"
				v.memory = 1024
				v.cpus = 1
			end
			control.vm.provision "shell", path: "./scripts/server.sh"
  end

  config.vm.define "shocquenSW" do |control|
			control.vm.hostname = "shocquenSW"
			control.vm.network "public_network", bridge: "eno1", ip: "192.168.56.111"
			control.vm.provider :libvirt do |v|
				v.name = "shocquenSW"
				v.memory = 1024
				v.cpus = 1
			end
			control.vm.provision "shell", path: "./scripts/agent.sh"
  end

end
