apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: p3
spec:
  project: default
  source:
    repoURL: 'https://github.com/souhoc/for-iot-shocquen.git'
    targetRevision: HEAD
    path: .
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true